// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IpAddressServiceClient is the client API for IpAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpAddressServiceClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type ipAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpAddressServiceClient(cc grpc.ClientConnInterface) IpAddressServiceClient {
	return &ipAddressServiceClient{cc}
}

func (c *ipAddressServiceClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/ipaddr.server.IpAddressService/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipAddressServiceClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/ipaddr.server.IpAddressService/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpAddressServiceServer is the server API for IpAddressService service.
// All implementations must embed UnimplementedIpAddressServiceServer
// for forward compatibility
type IpAddressServiceServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedIpAddressServiceServer()
}

// UnimplementedIpAddressServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIpAddressServiceServer struct {
}

func (UnimplementedIpAddressServiceServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedIpAddressServiceServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedIpAddressServiceServer) mustEmbedUnimplementedIpAddressServiceServer() {}

// UnsafeIpAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpAddressServiceServer will
// result in compilation errors.
type UnsafeIpAddressServiceServer interface {
	mustEmbedUnimplementedIpAddressServiceServer()
}

func RegisterIpAddressServiceServer(s grpc.ServiceRegistrar, srv IpAddressServiceServer) {
	s.RegisterService(&IpAddressService_ServiceDesc, srv)
}

func _IpAddressService_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpAddressServiceServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipaddr.server.IpAddressService/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpAddressServiceServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpAddressService_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpAddressServiceServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipaddr.server.IpAddressService/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpAddressServiceServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpAddressService_ServiceDesc is the grpc.ServiceDesc for IpAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipaddr.server.IpAddressService",
	HandlerType: (*IpAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _IpAddressService_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _IpAddressService_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "IpAddressService.proto",
}
